# Config file for automatic testing at travis-ci.org

language: python

python:
  - 2.7
  - 3.5

env:
  - TOXENV=django111
  - TOXENV=django20
  - TOXENV=django21
  - TOXENV=django22

matrix:
  exclude:
    - python: 2.7
      env: TOXENV=django20
    - python: 2.7
      env: TOXENV=django21
    - python: 2.7
      env: TOXENV=django22
  include:
    - python: 3.5
      env: TOXENV=quality
    - python: 3.5
      env: TOXENV=docs

cache:
  - pip

branches:
  only:
    - master
    - /v?^\d+\.\d+(\.\d+)?(-\S*)?$/

install:
  - pip install -r requirements/travis.txt

script:
  - tox

after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: xTsxnYnbjFurXNfULwxj3KgMPeDKxDxxW+gcq492h4mUpQChgM2/P/hxyLpRTY1amz8YYE7nr/ZMpQXC24b7LVly2lap5I9COcv9EP8SY7rvy4nmQjDRbQfibU8lvcLXkYiuB6B58iC+EzdA0VGR495hy+OJ3pJNyhstLjmhJEHmcFUIgZMipS3K0XjpWKI78xnOQ8yZXHu7S1PoNCYpQn5FuGTHcembHzDYtYSpeDIj2pyoATzL+X1Uy19Yjluf8XR4juCWAMlZqpGMC4+kNEncm2sTdBrdS2zY8P+ge3pMdLeAOifaQDHdAOiRE0f/MScTVCWv0D2H9ytJcAymuNRP0U1+luo8GZVh0eqY1aLX+O1iZOXO6GpNY1dWxbT94O7Ajxob5/b+1buTOgaD6m8dtwDCdzGicSZkdQvxEtoU/Eav8efGp/HTR+lp+U0jx6fpBnfSYfgCsEozjivfx1ETIHG9sQsraxFeIxyk1mF4nPwdyX90/h2ysdhojz2/5V1L75RnczUuGQXeT0H+o+9pubqOqLi0LC3ffx54fgBAIzzCRGkBB+XcKqMkmBgIJcE5/BQ9CkupAniZA8ulPvFs0FVj93bWMyY9o9ctvBlK1KuDw11sgkfp/niVbSCowN+wT9Jw1oGnFYD+BMXjt31V7DMySPQlowgF+/JXKec=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: '$TOXENV = quality'
