language: python
matrix:
  include:
  - python: 3.5
    env: TOX_ENV=py35-django22-celery31
  - python: 3.5
    env: TOX_ENV=py35-django22-celery40
  - python: 3.5
    env: TOX_ENV=py35-django22-celery42
  - python: 3.5
    env: TOX_ENV=py35-django22-celery43
  - python: 3.5
    env: TOX_ENV=py35-django22-celery44
  - python: 3.8
    env: TOX_ENV=py38-django22-celery42
  - python: 3.8
    env: TOX_ENV=py38-django22-celery43
  - python: 3.8
    env: TOX_ENV=py38-django22-celery44
  - python: 3.5
    env: TOX_ENV=quality
  - python: 3.5
    env: TOX_ENV=docs
cache:
- pip
branches:
  only:
  - master
  - "/v?^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install:
- pip install -r requirements/travis.txt
script:
- tox -e $TOX_ENV
after_success:
- codecov
deploy:
  provider: pypi
  user: edx
  password:
    secure: aNtU8hLgEXPSre5UWviuliSmCAGH7I9Q+mcXGYc0UcuStntpJDsC28Bwh72VfRiONJhwDTQNPZCkd8GL71nk/bGxFk1OwVXzTG3KZMNx4rB/ASs8QRvsdGQFZ/aOISlPEbhyEWBh2kQqVboINpLLbklQNjPsok/EzPo0tpSpvDiX/suYAE+byOXE0mdFwDaXENDTizieol4jYnL6KnprVKo9MpLQeqnTyHODSM/FugOTmqx7CPssx8+Yz/ky8ZSnX256cmKcpsDEM/7t7sHqIEOvY7DeOBy1PiRNk+Qo2di2XNVVFtYT1/bE9thRpuzNpadxPWTZQD8/pu7joECg6FnC/X88NRsOctx4woMbqkD7i6qKQnYczOhhTUr6ZoLXCiP876cedsycoYEfh4zTnRvCDtSRsnCHVm6TtV6PrMSrRj/wxbFxuBBDWNwKTj+zbkQC71rg6BFuqu0VftQhJjA2HQOVTL1we4ySwOKxpdlDVd81UM3C6sMmJx+Wv+MeTbNXTkbj/Ra7NolN7+CkMaKeUMDvM3aAxsSvq7pBdbgiEJ1reptSzQfdEhXV8rwwWzkmIzqjoXThO9Guod1XDeGb9OR/9RLZLvRuF75IrUyBl6VYVJVkn48DZHDPX9y8qtxGPek3OnJkM+G8lLaHbpiQyi7JRPMD9bNpimJlhQ4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TOXENV = quality"
