name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.8"]
        toxenv: [
          "django22-celery44-drf39", "django22-celery44-drf310",
          "django22-celery44-drf311", "django22-celery44-drf312",
          "django22-celery50-drf39", "django22-celery50-drf310",
          "django22-celery50-drf311", "django22-celery50-drf312",
          "quality", "docs"
        ]

    steps:
    - uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: pip install -r requirements/pip.txt

    - name: Install Dependencies
      run: pip install -r requirements/ci.txt

    - name: Run Tests
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox

    - name: Run coverage
      if: matrix.python-version == '3.8' && matrix.toxenv == 'django22-celery44-drf312'
      uses: codecov/codecov-action@v1
      with:
        flags: unittests
        fail_ci_if_error: true

  commit-lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install commintlint-cli
        run: npm install -g @commitlint/cli
      - name: Install commintlint-config
        run: npm install -g @commitlint/config-conventional
      - name: Lint commit messages
        run: for commit in $(git log --no-merges --pretty=format:%H remotes/origin/master..); do git show -s --pretty=format:%B $commit | commitlint -V; done
